### ISSUE TITLE
joint intervention on multiple variables

### ISSUE THREAD

**Issue by sally741** [CausalInference/gfoRmula#22]
Hello, 
My colleague and I have been able to run this package with interventions on a single static intervention. However, when we tried to run it for a joint intervention on two variables, we got the following error:
ERROR in length(intvar==1) && intvar=="none": (length=2) in coercion to "logical(1)"
Does the current version of the package work for joint interventions? I believe we carefully followed the syntax for how to specify a joint intervention, so we wondered if maybe there was an update to R that broke this particular functionality in the gfoRmula package, or if there is some obvious mistake we could've made in specifying the interventions that would result in this type of error.

Also, as a separate issue: when running static interventions on one variable, we've gotten what seem like paradoxical results: usually, the intervention "treat everyone at all time points" and the intervention "never treat anyone" give averages of the (continuous) outcome at end of follow-up that are on opposite sides of the average under the natural course. But for one of our intervention variables, these interventions give averages on the same side of the natural course average. That seems like it should be mathematically impossible. Do you have any thoughts on this? Have you observed this issue before?

Thank you!
Best wishes,
Sally

**Comment by stmcg** [comment]
Hi Sally,

Thanks for posting. 

You're right that there was a bug in the package for joint interventions! It arose from a recent update to the package. I just made an update in the package to fix the bug. Does your code run okay now?

As far as the two interventions giving estimates on the same side as the natural course average -- It seems strange, although I don't believe it is mathematically impossible. Some initial questions I'd have when seeing these results would be: Are the differences from the natural course mean very large? Are the CIs around the outcome means large?

Last, apologies for the delay in getting to your other post. I got back in town this week, and am now getting caught up. I see that you just marked your last post as resolved. So I'm assuming you don't need any more help with it, but let me know otherwise.

Best,
Sean

**Comment by sally741** [comment]
Hi Sean,
(sorry for the delay, I've been sick all week)
Thank you! We will ask the sysadmin to install the updated version. 
We've also just discovered that if we include another lag of the intervention variable in the outcome model, then the results for the two interventions go in opposite directions as expected.

I suspect some of the errors we had previously were due to collinear covariates, but we seem to have found ways to tweak our analysis to avoid those errors now. 

I'll let you know if we have any further issues with the joint intervention.
Thanks again!
Best wishes, 
Sally

**Comment by sally741** [comment]
Hello again Sean,
The sysadmin says the most up-to-date version on the CRAN site is the one we have installed. So I take it the update you made is just here on github? I guess we'll direct the sysadmin to what's here?

**Comment by rwlogan** [comment]
If you use the version on GitHub, make sure you are using the code from the master branch. The other branches are for testing new code and have not been completely tested.

Thanks,
Roger

**Comment by sally741** [comment]
Thanks, Roger!

**Comment by stmcg** [comment]
> Hello again Sean, The sysadmin says the most up-to-date version on the CRAN site is the one we have installed. So I take it the update you made is just here on github? I guess we'll direct the sysadmin to what's here?

That's right. This update is just on GitHub currently. In case helpful, the README file in this repository lists a line of code which can be used to download the GitHub version of the package (from the master branch)

**Comment by sally741** [comment]
Great news: the updated version does work for the joint intervention! Thank you so much for making that update!

**Comment by stmcg** [comment]
That's great to hear! Thanks for letting us know
