### ISSUE TITLE
Issue with "absorbing" variable type

### ISSUE THREAD

**Issue by sally741** [CausalInference/gfoRmula#24]
Hi again,
I mentioned this problem in an earlier thread but since it is a different error, I think it deserves its own thread.

We are getting the following error when we try to assign a certain variable (one of our intervention variables) an "absorbing" type, but not if it is assigned to be "binary". (It is actually an absorbing variable, but we've been running it as binary to avoid the error.)

Error in seq. int(min(dim(R))): "from" must be a finite number
which apparently arises from whatever caused the following warning:
min(dim(R)): no non-missing arguments to min; returning Inf.

My best guess is that it could be a positivity problem? (at a certain point, I think it has value 1 for everyone? and it's definitely 0 for everyone at the beginning) But then why wouldn't this error occur if the covariate is considered binary? Do you have any thoughts?

**Comment by stmcg** [comment]
Hi Sally,

I think I've gotten to the bottom of this -- 

First, I believe this error message is arising when simulating this covariate. One scenario where this occurs is when the fitted covariate model has a coefficient with a value of NA. I suspect that this could also arise in scenarios where the fitted covariate model has estimated coefficients that are extreme (eg, very large). If you set `model_fits = TRUE` (which allows you to access the fitted covariate models), this error message should go away although you may get new warning messages due to NA or extreme coefficients. In brief, receiving this error message as opposed to the warnings relates to how the package clears memory when you don't need to access the fitted covariate models. 

I'd suggest taking a look at the fitted covariate models when using the "absorbing" covtype and see if anything looks unusual, such as coefficients with a value of NA.

Second, I just fixed a bug in the package when multiple modelling restrictions are applied to a single covariate. One such restriction arises when using an "absorbing" covtype (as the package only fits the model with up to when the covariate achieves a value of 1). If you had another restriction in place for this covariate, the version of the package that you were using likely wasn't being restricted to the right subset of the data. This could have resulted in obtaining extreme or NA coefficients in your model. The current GitHub version of the package includes this bug fix.

Hope this resolves your question!

Best,
Sean

**Comment by sally741** [comment]
Thank you, Sean! We'll try the new version and use model_fits=TRUE to see if we can figure out where things are going wrong.
