### ISSUE TITLE
how to model censoring

### ISSUE THREAD

**Issue by dzugna** [CausalInference/gfoRmula#26]
The aim of my study is to develop/validate a prognostic model under different treatment regimes. Hence I'm interested in simulating different datasets in presence of competing events and dependent censoring.
From your previous suggestions it is clear to me how to consider time to competing events: we suppose to be interested in the mortality within 5 years since diagnosis, for each subject 5 records will be simulated (if we consider year as time-scale), Y and D can assume value 1 for multiple record for each subject but we have to interrupt the observation at the first value 1 (to calculate hazard or risk).  
For each subject without main event/competing events we have 5 records.  We have two options, using or not using IPW, depending on the underlying assumption of marginal or conditional independence of censoring. However using the IPW does not affect the simulated data but only the estimates after simulation. Hence I was wondering whether you could explain me how we use the simulated data in the two approaches:
1. under marginal independence we calculate the hazard/risk by dropping the censored subjects (without any Y or D=1) ?
2. under conditional independence we calculate the hazard/risk by applying  weights that we calculated on the observed data to the simulated data?If yes, in practice we keep the 5 records for each subject and apply a weight calculated on observed data  according to the specific characteristics of the subject and the time of observation?

Thanks in advance

**Comment by rwlogan** [comment]
I am sorry I didn’t respond to your previous message but I have been busy with other projects. Is it your goal to be using the package to use the simulated data for doing what you ask below, or are you trying to get the package to do what is listed in 1 and 2?

**Comment by dzugna** [comment]
absolutely no problem, thank you very much for your availability and
timeliness.
I would like to understand how the package works regarding censoring to
subsequently understand how to use the simulated data for my purpose. Are
the weights used in the IPW calculated on the observed data and then are
they applied to simulated data to calculate hazard and risk?
It is clear to me that both the hazard and the risk are calculated by
interrupting the observation at the first event (the first 1 simulated),
while it is not clear to me how it deals with censoring, how we can
distinguish between administrative censoring and loss to follow-up after
simulating data. I think we cannot, hence I thought about the point 1. and
2. under the two different scenarios, marginal independent censoring and
conditional indipendent censoring.

 I hope I was clear, if not I'm sorry,
thanks


Il lun 11 dic 2023, 18:06 rwlogan ***@***.***> ha scritto:

**Comment by rwlogan** [comment]
My understanding is that the ipw weights are only being used as a diagnostic tool when looking at the graphs that can be output. This is a tool to check how well the models for the covariates, and outcomes(event and potentially competing event) match up with the observed data. The weights are not being used for the risk or the hazard ratio.

The use of the simulated outcome and the competing risk are only being used in the hazard ratio. For ease of calculating the hazard ratio, these two values, Y and D are calculated in the code for the simulated data. This is so a separate pass through the simulated data is not required to slow down the program. You should ignore that it is possible for there to be multiple times when Y = 1 or D = 1. This is not trying to simulate multiple outcomes.

In terms of how the hazard is being calculated there is no use of any real censoring other than due to end of follow-up. When compevent_cens = TRUE,  the competing event is considered to be a censoring variable and not used in the hazard. In this case the hazard will be based on a variable that has two levels: 1 = event happens, 0 = censored due to end of follow-up. When compevent_cens = FALSE, the competing event is not assumed to be a censoring variable and the variable being used in the hazard ratio now has three levels: 1 = event happens, 0 = censored due to eof, 2 = competing event happens. In none of these is there any time of censoring due to lost to follow-up.

In the data for the hazard there are  three variables being used: time of the “event”, where event is event , censoring due to eof, or potential competing event. The second variable is the time of this “event”. When there is no Y=1 or D = 1 this time is the value of time_points being used in the package call. The third variable is a binary variable to indicate the two interventions that are being compared.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by jerbear1992** [comment]
Hi Roger, happy news years and hope all is well. I'm sorry to butt in but I wanted to just confirm with you - the gformula surv function does not indeed account for censoring due to loss to follow-up before end of study? As you said there is either if comp event happens, if the actual outcome event happens, or censored due to end of the study?

If so, in a study with a portion of individuals who were loss to follow up before end of study due to say drop out, are we to exclude these individuals from analysis?

**Comment by rwlogan** [comment]
Hi,
In the Monte-Carlo stage of the surv function the calculation of the risk and hazard ratio do not use any censoring due to lost to follow-up. In the hazard ratio, censoring due to eof is being used, but this is due to the setting of time_points for the length of follow-up to simulate. I suppose you could consider time_points – 1 as being the end-of-follow-up in a study. It is not required to be related to the admin eof in the supplied data. In the case of an eof type outcome, then all non-censored subjects need to have their outcome measured at timepoints – 1.

For the data you use, I would not remove those who are censored due to lost to follow-up since these subjects contribute information to the outcome and covariate models. When these subjects are also used for the simulation stage, a complete follow-up (until time_points) is generated, so they will not be censored.

Hope this helps.

Roger

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

________________________________
