### ISSUE TITLE
avoidable number of cases

### ISSUE THREAD

**Issue by chenlan26** [CausalInference/gfoRmula#35]
Hello, 
I'm using the gfoRmula package to examine the effects of air pollution control policy on all-cause death and cause-specific death. I calculated the death number by the following equation: sum(sim_data$`Natural course`$Y) , and then calculated the avoidable death number by minusing the death number between natural course and intervention course.  I considered the competing event in cause-specific death estimation. But the aviodable number of cause-specific death is larger than all-cause death. I did not find any problem with my code yet. Is there any reason or tips for this result? Thank you!

Best,
Alan

**Comment by stmcg** [comment]
Hi Alan,

I think the crux of the issue is that the values of Y and D in the simulated data sets aren't meant to be used in this way. They are actually not used in calculating the survival curves at all. Rather, they are just used internally when estimating the HR.

One issue with using the simulated Y and D is that individuals are kept in the simulated data set at all time points, even after simulating Y=1 or D=1 (when the package is estimating hazard ratios, it internally re-formats the data set appropriately). This means, for example, that some individuals will have Y=1 counted multiple times when performing your calculation. I see a few other issues as well if I'm understanding right.

I'd instead work with the survival curve / risk estimates for this. 

Best,
Sean

**Comment by chenlan26** [comment]
Hi Sean,


Thank you a lot for your reply timely. I've got the points you posted in the mail. I will conduted the analyses of survival curve / risk estimates instead.


Thank you very much!






 Best Regards，
Lan Chen&nbsp;
Department of &nbsp;Epidemiology
School of Public Health
SUN YAT-SEN UNIVERSITY
Tel:86+15764325648

 

&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Thu, Aug 1, 2024 11:46 AM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [CausalInference/gfoRmula] avoidable number of cases (Issue #35)

&nbsp;



 
Hi Alan,
 
I think the crux of the issue is that the values of Y and D in the simulated data sets aren't meant to be used in this way. They are actually not used in calculating the survival curves at all. Rather, they are just used internally when estimating the HR.
 
One issue with using the simulated Y and D is that individuals are kept in the simulated data set at all time points, even after simulating Y=1 or D=1 (when the package is estimating hazard ratios, it internally re-formats the data set appropriately). This means, for example, that some individuals will have Y=1 counted multiple times when performing your calculation. I see a few other issues as well if I'm understanding right.
 
I'd instead work with the survival curve / risk estimates for this.
 
Best,
 Sean
