### ISSUE TITLE
Possible to extract simulated data? 

### ISSUE THREAD

**Issue by pychan-polly** [CausalInference/gfoRmula#36]
Thank you for developing and maintaining the gfoRmula package. I find it easy to use and the paper (McGrath et al., 2020) has been of a great help to me. 

I am working on an analysis with an end-of-follow-up binary outcome but I may also want to look at the outcome trajectory over time. I was trying to figure out if there is a way to extract simulated covariates (more specifically, the history of the outcome at each time point before the end of the follow up) and the outcome but I think I can only specify `sim_data_b = TRUE` when I don't use bootstrapping (`nsamples = 0`). 

My question is, is there any way to extract simulated data from `gformula()` when I use bootstrapping?

**Comment by stmcg** [comment]
Thank you! 

You're correct that the package is not able to return the simulated data sets from the bootstrap replicates. I believe it was set up this way because otherwise the memory requirements often become too large. 

If you need to access the simulated data sets from the bootstrap replicates, I think the "easiest" approach would be to manually perform bootstrapping outside of the `gformula` function

**Comment by pychan-polly** [comment]
Thank you. I figured that would probably be the easiest way but good to get a confirmation from you. 

I also have one other unrelated question. I'm a bit puzzled by the different results (specifically, the "g-form mean") I got between two test runs with different numbers of `nsample` but the same seed specification. I thought the mean would be the same but only the 95% CI would differ. Do I misunderstand something?

**Comment by pychan-polly** [comment]
Hello Sean, I'm following up to see if I can get an answer on my previous question. Much appreciated.

**Comment by stmcg** [comment]
Apologies for the delay! Thanks for asking this and following up. 

I'm also finding that the point estimates slightly differ when changing `nsamples`. This is due to a missing `set.seed` call in the `gformula` function. If curious about the specifics -- While the package uses the same seed (regardless of `nsamples`) in the function used to simulate the data sets for the point estimates, the selection of IDs to include in the simulated data set occurs before that function which doesn't have a `set.seed` call before it (which would be necessary to make the results identical regardless of `nsamples`)

I should be able to push an update to the package fixing this within the next few days. Currently in the middle of adding a new feature

**Comment by pychan-polly** [comment]
Thank you and it makes sense! Looking forward to the update (and the new feature).

**Comment by stmcg** [comment]
Giving a heads up that I made the update. Is it working as expected now?

**Comment by pychan-polly** [comment]
I just got a chance to install the latest version (shown as 1.1.0 on my R) and tested it. For some reason I am still getting different g-form means with different `nsamples ` specifications.

**Comment by stmcg** [comment]
My apologies, one more fix was needed. Can you install the latest version and try again?

**Comment by pychan-polly** [comment]
Thank you Sean! I tested and now the g-form means are consistent.
