### ISSUE TITLE
Specifying a variable of covtype 'custom' and 'absorbing' 

### ISSUE THREAD

**Issue by njawadekar** [CausalInference/gfoRmula#42]
Hello,
Within my gformula function, I am looking to specify a variable which is both 'custom' and 'absorbing'. In other words, I am trying to specify my own user-written prediction function for this variable (using something other than glm, as described in section C.7 of your supplement), and in addition, I would also like to  restrict these predictions to records where the value of the covariate at k −1 (the lagged value) is 0. And then thereafter, once a 1 is first generated, the covariate value at that time and all subsequent times would be set to 1.

In your package, is it even possible to define a single covariate as both 'custom' and 'absorbing', as I have described above?

**Comment by stmcg** [comment]
Yes, you can specify a custom model for the covariate and have it be an absorbing variable. I'd specify the covariate type as "custom", and then in the custom fit function just restrict the model fitting to records up to the first 1. In the custom predict function, you'd need to manually add a condition to only predict if the previous value of that covariate is 0 (otherwise set it equal to 1). That is, you can enforce the absorbing aspect of the covariate in your custom fit and predict functions. Does that make sense?

**Comment by njawadekar** [comment]
Yes, makes sense. Thank you!
